Repository xaankoow/segmento-nuxt, pull requests merged in 2023-10, with the labels that each got.

#141 created function and changed some designed
  components/Dropdown/DropdownIndexTwo.vue
  components/Input/Checkbox/index.vue
  components/Input/Radio/index.vue
  components/Input/Select/index.vue
  pages/affiliate-panel/index.vue
  pages/robot-file-generator/index.vue
Labels: enhancement

#143 Feature, Fix and Update
  .env.example
  assets/Config/languages.json
  assets/icons/copy.svg
  assets/icons/google.png
  assets/icons/warning.png
  components/According.vue
  components/DataTable/Row.vue
  components/Input/Text/Area/Liner.vue
  components/Navbar/Right/Content/Department.vue
  components/Navbar/Right/SvgItem.vue
  layouts/default.vue
  pages/disavow-builder/index.vue
  pages/g-ads-preview/index.vue
  pages/google-title-builder/index.vue
  pages/keyword-research/index.vue
  pages/serp-preview/index.vue
Labels: bug, enhancement

#144 Liner Component Fixed.
  components/Input/Text/Area/Liner.vue
  pages/disavow-builder/index.vue
  pages/idea-generator/index.vue
Labels: bug

#145 Bulk copy writer
  components/Diagram/tree.vue
  components/Input/Radio/index.vue
  components/Input/Text/Area/Liner.vue
  layouts/default.vue
  pages/bulk-copy-writer/index.vue
Labels: enhancement

#146 Copy Array component
  components/Copy/Array.vue
  layouts/default.vue
  pages/index.vue
Labels: bug, enhancement

#150 Add site feature!
  assets/css/main.css
  components/Input/Checkbox/index.vue
  components/Input/Radio/index.vue
  components/Input/Text/Marked.vue
  components/Popup/index.vue
  components/widgets/AddSite/First.vue
  components/widgets/AddSite/Keywords.vue
  components/widgets/AddSite/LighthousePages.vue
  components/widgets/AddSite/MoneyPages.vue
  components/widgets/AddSite/index.vue
  layouts/default.vue
  pages/bulk-copy-writer/index.vue
  pages/disavow-builder/index.vue
  public/images/LighthousePagesStep.png
  public/images/MoneyPageStep.png
  public/images/checked.png
  public/images/competitorsStep.png
  public/images/keywordStep.png
  public/images/site.png
  widget/Workspace/Add/Steps/One.ts
  widget/Workspace/Add/Steps/Two.ts
Labels: bug, enhancement

#151 Add workspace completed!
  Api/Request.ts
  assets/Config/languages.json
  components/According.vue
  components/Copy/index.vue
  components/Navbar/Right/Content/Department.vue
  components/Popup/Message/index.vue
  components/Popup/index.vue
  components/Svg/Labeled.vue
  components/widgets/AddSite/header.vue
  components/widgets/AddSite/index.vue
  interfaces/Models/Config/Limit.ts
  layouts/default.vue
  locales/fa-IR.json
  pages/Profile/Change-phone-number.vue
  pages/auth/forget.vue
  pages/auth/login.vue
  pages/google-suggest/index.vue
  pages/google-title-builder/index.vue
  pages/keyword-research/index.vue
  pages/money-pages/[slug].vue
  pages/robot-file-generator/index.vue
  store/ConfigStore.ts
  tailwind.config.js
  widget/Workspace/Add/PagePanel.ts
  widget/Workspace/Add/Steps/One.ts
  widget/Workspace/Add/Steps/Three.ts
  widget/Workspace/Add/Steps/Two.ts
Labels: bug, enhancement

#152 Closing Accordions in navbar Completed!
  assets/Config/languages.json
  components/Accordion.vue
  components/Dropdown/index.vue
  components/Navbar/Right/Content/Department.vue
  layouts/default.vue
Labels: enhancement
