Repository xaankoow/segmento-nuxt, pull requests merged in 2023-09, with the labels that each got.

#123 Fix and Update
  assets/Config/languages.json
  assets/css/main.css
  components/Navbar/Right/Content/Department.vue
  components/Navbar/Top/index.vue
  components/Plan/index.vue
  layouts/default.vue
  locales/fa-IR.json
  pages/buy-subscription/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/index.vue
  pages/keyword-research/index.vue
  pages/title-copy-writer/index.vue
Labels: bug, enhancement

#125 Update payment link buy subscription.
  pages/buy-subscription/index.vue
Labels: enhancement

#122 Disavow Page
  assets/Config/languages.json
  assets/icons/reset.svg
  assets/icons/warning.png
  assets/icons/warning.svg
  pages/disavow-builder/index.vue
Labels: enhancement

#127 Fix and Update and Feature!
  Controllers/HTMLController.ts
  assets/Config/languages.json
  assets/Fonts/Intel.css
  assets/Fonts/YekanWebFonts/IRANYekan.html
  assets/Fonts/YekanWebFonts/WebFonts.png
  assets/Fonts/YekanWebFonts/css/fontiran.css
  components/Input/Text/Area/Liner.vue
  components/Input/Text/Area/index.vue
  components/Navbar/Top/index.vue
  components/Plan/index.vue
  components/Tab/Item.vue
  layouts/default.vue
  nuxt.config.js
  pages/buy-subscription/index.vue
  pages/disavow-builder/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/keyword-research/index.vue
  pages/rank-tracker/competitors.vue
  pages/rank-tracker/keyword.vue
  pages/rank-tracker/overview.vue
  public/images/AuthBackground.png
Labels: bug, documentation, enhancement

#128 Add `ExtensionTools` composable
  components/Plan/index.vue
  composables/ExtensionTools.ts
  pages/buy-subscription/index.vue
Labels: enhancement

#129 serp builder
  assets/icons/google.png
  pages/serp-preview/index.vue
Labels: enhancement

#133 Fix and Update
  components/Input/Text/Area/Liner.vue
  components/Input/Text/Area/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/serp-preview/index.vue
  pages/title-copy-writer/index.vue
Labels: bug

#134 Update, Fix and Feature
  components/Input/Text/Area/Liner.vue
  components/Input/Text/Area/index.vue
  components/Input/Text/index.vue
  layouts/default.vue
  pages/auth/login.vue
  pages/buy-subscription/index.vue
  pages/disavow-builder/index.vue
  pages/google-title-builder/index.vue
  pages/serp-preview/index.vue
Labels: bug, enhancement

#135 Update and Feature
  components/Input/Text/Progressed.vue
  components/Input/Text/index.vue
  pages/Profile/Change-password.vue
  pages/Profile/index.vue
  pages/auth/forget.vue
  pages/auth/signup/index.vue
  pages/auth/signup/verify.vue
  pages/serp-preview/index.vue
  tailwind.config.js
  widget/Workspace/Add/Steps/One.ts
Labels: enhancement

#136 Api refactor
  .env.example
  Api/Request.ts
  Api/ResponseModel.ts
  assets/images/iphoneImg.png
  components/Input/Text/Area/index.vue
  components/Input/Text/Progressed.vue
  components/Plan/index.vue
  layouts/default.vue
  pages/auth/forget.vue
  pages/auth/login.vue
  pages/auth/signup/index.vue
  pages/auth/signup/verify.vue
  pages/bulk-copy-writer/index.vue
  pages/buy-subscription/index.vue
  pages/g-ads-preview/index.vue
  pages/google-suggested-words/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/keyword-research/index.vue
  pages/serp-preview/index.vue
  pages/subscription-status/index.vue
  pages/title-copy-writer/index.vue
Labels: enhancement

#137 Api refactor
  Api/Request.ts
  components/Plan/index.vue
  pages/auth/forget.vue
  pages/auth/login.vue
  pages/auth/signup/verify.vue
  pages/buy-subscription/index.vue
  pages/google-suggested-words/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/keyword-research/index.vue
  pages/title-copy-writer/index.vue
Labels: bug, enhancement

#138 Api refactor
  .env.example
  Api/Request.ts
  Api/ResponseModel.ts
  assets/images/iphoneImg.png
  components/Input/Text/Area/index.vue
  components/Input/Text/Progressed.vue
  components/Plan/index.vue
  layouts/default.vue
  pages/auth/forget.vue
  pages/auth/login.vue
  pages/auth/signup/index.vue
  pages/auth/signup/verify.vue
  pages/bulk-copy-writer/index.vue
  pages/buy-subscription/index.vue
  pages/g-ads-preview/index.vue
  pages/google-suggested-words/index.vue
  pages/google-title-builder/index.vue
  pages/idea-generator/index.vue
  pages/keyword-research/index.vue
  pages/serp-preview/index.vue
  pages/subscription-status/index.vue
  pages/title-copy-writer/index.vue
Labels: enhancement
