Repository xaankoow/segmento-nuxt, pull requests merged in 2023-08, with the labels that each got.

#70 fix
  components/FileUploader/index.vue
  components/Navbar/Top/index.vue
  pages/auth/forget.vue
  pages/auth/login.vue
  pages/auth/signup/index.vue
Labels: bug

#71 Fix
  Api/Request.ts
  assets/Config/languages.json
  components/Navbar/Right/Content/Department.vue
  components/Navbar/Top/index.vue
  components/Popup/index.vue
  components/Tab/Item.vue
  interfaces/Models/Config/Plan.ts
  interfaces/Models/Config/Workspace.ts
  interfaces/Models/Wallet.ts
  layouts/default.vue
  middlewares/Auth.js
  nuxt.config.js
  pages/auth/login.vue
  pages/auth/signup/index.vue
  pages/auth/signup/verify.vue
  pages/buy-subscription/index.vue
  pages/index.vue
  pages/keyword-research/index.vue
  pages/rank-tracker/competitors.vue
  pages/rank-tracker/keyword.vue
  pages/rank-tracker/overview.vue
  pages/workspace/add.vue
  store/ConfigStore.ts
Labels: bug, enhancement

#72 Fix available pages
  assets/Config/languages.json
  layouts/login.vue
  pages/Profile/Change-password.vue
  pages/Profile/Change-phone-number.vue
  pages/Profile/index.vue
  pages/auth/login.vue
  pages/auth/signup/index.vue
  pages/auth/signup/verify.vue
  pages/index.vue
  pages/money-pages/[slug].vue
  pages/money-pages/index.vue
Labels: bug

#67 Line
  components/Chart/Line.vue
Labels: bug

#69 progress
  components/Chart/Progress.vue
  components/RadialProgress.vue
Labels: enhancement

#59 add money page
  assets/css/main.css
  pages/money-pages/index.vue
Labels: enhancement

#80 Update & Fix
  Controllers/HTMLController.ts
  Models/Package.ts
  assets/Config/languages.json
  assets/css/main.css
  components/Navbar/Top/index.vue
  components/Plan/index.vue
  components/RadialProgress.vue
  components/Tab/Item.vue
  interfaces/Models/Pack.ts
  interfaces/Models/Package.ts
  interfaces/Models/Plans.ts
  layouts/default.vue
  pages/auth/login.vue
  pages/buy-subscription/index.vue
  pages/keyword-research/index.vue
  pages/rank-tracker/keyword.vue
Labels: bug, enhancement

#81 Step one to add workspace
  Api/ResponseModel.ts
  pages/index.vue
  tailwind.config.js
  widget/Workspace/Add/Steps/One.ts
Labels: enhancement

#82 navbars scroll get fixed.
  components/Navbar/Top/index.vue
  layouts/default.vue
Labels: bug

#83 Fix
  pages/keyword-research/index.vue
Labels: bug

#84 some pictures get changed
  public/favicon.ico
  public/images/AuthBackground.png
Labels: bug, documentation

#86 LimitCounter component
  components/LimitCounter.vue
  components/Navbar/Top/index.vue
  pages/keyword-research/index.vue
Labels: enhancement

#94 Add third step to create workspace
  assets/Config/languages.json
  pages/index.vue
  public/images/add_money_page.png
  public/images/step_two_add_workspace.png
  widget/Workspace/Add/Steps/One.ts
  widget/Workspace/Add/Steps/Three.ts
  widget/Workspace/Add/Steps/Two.ts
Labels: bug, enhancement

#95 update auth pages
  assets/Config/languages.json
  components/Navbar/Right/Content/Home.vue
  layouts/login.vue
  pages/auth/forget.vue
  pages/auth/signup/verify.vue
Labels: documentation

#98 Idea generator page created
  .env.example
  Api/Request.ts
  assets/Config/languages.json
  components/According.vue
  components/Navbar/Top/index.vue
  layouts/default.vue
  nuxt.config.js
  pages/idea-generator/index.vue
  widget/Workspace/Add/Steps/Three.ts
Labels: enhancement

#101 Fix & Config
  Api/Request.ts
  components/Plan/index.vue
  nuxt.config.js
  pages/buy-subscription/index.vue
  pages/idea-generator/index.vue
Labels: bug, enhancement

#105 Update and Feature
  assets/Config/languages.json
  layouts/default.vue
  pages/g-ads-preview/index.vue
  pages/serp-preview/index.vue
Labels: enhancement

#111 Store limit
  interfaces/Models/Config/Limit
  interfaces/Models/Config/Plan.ts
  interfaces/User.ts
  pages/auth/login.vue
  pages/auth/signup/verify.vue
  store/ConfigStore.ts
Labels: enhancement

#112 Update buy package page
  components/Plan/index.vue
  pages/buy-subscription/index.vue
Labels: enhancement

#115 Fix
  pages/idea-generator/index.vue
Labels: bug

#118 Debug
  components/Navbar/Top/index.vue
  layouts/default.vue
  pages/idea-generator/index.vue
  pages/keyword-research/index.vue
  pages/title-copy-writer/index.vue
Labels: bug

#120 Main Page Added.
  assets/Config/languages.json
  layouts/default.vue
  pages/google-title-builder/index.vue
  pages/index.vue
Labels: bug, enhancement

#119 Refactor buy subscription
  Api/Request.ts
  Api/ResponseModel.ts
  components/Plan/index.vue
  pages/buy-subscription/index.vue
Labels: bug, enhancement

#121 Subscription status and some updates
  .env.example
  assets/Config/languages.json
  assets/css/main.css
  components/Navbar/Top/index.vue
  components/Plan/index.vue
  components/Progress/Radial/index.vue
  layouts/default.vue
  locales/fa-IR.json
  nuxt.config.js
  package.json
  pages/auth/login.vue
  pages/auth/signup/verify.vue
  pages/bulk-copy-writer/index.vue
  pages/buy-subscription/index.vue
  pages/money-pages/[slug].vue
  pages/money-pages/index.vue
  pages/rank-tracker/overview.vue
  pages/subscription-status/index.vue
  pages/title-copy-writer/index.vue
Labels: enhancement
