Repository xaankoow/segmento-nuxt, pull requests merged in 2024-04, with the labels that each got.

#166 Radial progress
  components/radialProgress/index.vue
  package.json
Labels: enhancement, good first issue

#167 Say Hi to Moneypages!
  components/Lighhouse/Shape/index.vue
  layouts/default.vue
  layouts/login.vue
  package.json
  pages/auth/signup/index.vue
  pages/money-pages/index.vue
  pages/money-pages/single.vue
Labels: bug, documentation, enhancement

#170 Say Hi to Subscription Status! (and a little more)
  components/widgets/AddSite/index.vue
  pages/money-pages/index.vue
  pages/money-pages/single.vue
  pages/subscription-status/index.vue
Labels: bug, documentation, enhancement

#172 `NODE_ENV` field added to `.env.example`
  .env.example
Labels: enhancement

#173 Update and Fix on `Moneypages/Single` && Say hi to `.htaccess`
  pages/money-pages/single.vue
  pages/subscription-status/index.vue
  public/.htaccess
Labels: bug, enhancement
